workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60

    environment:
      java: 17

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - chmod +x gradlew
      - ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
